// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nilnprhcyrsgdalguojh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbG5wcmhjeXJzZ2RhbGd1b2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNzMxNTEsImV4cCI6MjA3ODg0OTE1MX0.gXmzY9fEigCG_21dWlN3xIEgpgS-V23-ktxb3naKHgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);